### ISSUE TITLE
Issue with accessing data for count plan with 'xs'

### ISSUE THREAD

**Issue by andrewmkiss** [NSLS-II-SRX/profile_collection#2] opened 2019-01-11 16:37 UTC
Observed during the Deployment 2019-1 with @mrakitin and @ke-zhang-rd.

Attn @tacaswell

If we count 2 times, everything works fine:
```py
BlueSky@SRX [10]: RE(bp.count([xs], num=2))                                                                                                                   
Transient Scan ID: 21731     Time: 2019/01/11 11:27:41
Persistent Unique Scan ID: 'd3acaf29-2ae9-4c76-8172-8520843bc947'
                                                                                                                                                              


Out[10]: ('d3acaf29-2ae9-4c76-8172-8520843bc947',)

BlueSky@SRX [11]: hdr = db[-1]                                                                                                                                

BlueSky@SRX [12]: hdr.table()                                                                                                                                 
Out[12]: 
                                 time                   ...                                               xs_channel3
seq_num                                                 ...                                                          
1       2019-01-11 11:27:44.960414648                   ...                    49ff664c-5b91-494e-9378-5bdadf7d2ff4/2
2       2019-01-11 11:27:46.095082760                   ...                    49ff664c-5b91-494e-9378-5bdadf7d2ff4/5

[2 rows x 28 columns]

BlueSky@SRX [13]: hdr.table(fill=True)                                                                                                                        
Out[13]: 
                                 time                        ...                                                                xs_channel3
seq_num                                                      ...                                                                           
1       2019-01-11 11:27:44.960414648                        ...                          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2       2019-01-11 11:27:46.095082760                        ...                          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

[2 rows x 28 columns]
```

However, when we count more than 2 times, there is a problem with accessing the data:
```py
BlueSky@SRX [7]: RE(bp.count([xs], num=3))
Transient Scan ID: 21733     Time: 2019/01/11 11:29:44
Persistent Unique Scan ID: '1065e146-92ba-490a-af0e-40602dadc994'
                                                                                                                                                              


Out[7]: ('1065e146-92ba-490a-af0e-40602dadc994',)

BlueSky@SRX [8]: hdr = db[-1]

BlueSky@SRX [9]: hdr.table()
Out[9]: 
                                 time                   ...                                               xs_channel3
seq_num                                                 ...                                                          
1       2019-01-11 11:29:48.544847250                   ...                    006106d7-3f09-4617-9662-d45c8a9325ae/2
2       2019-01-11 11:29:49.685327768                   ...                    006106d7-3f09-4617-9662-d45c8a9325ae/5
3       2019-01-11 11:29:50.809357643                   ...                    006106d7-3f09-4617-9662-d45c8a9325ae/8

[3 rows x 28 columns]

BlueSky@SRX [10]: hdr.table(fill=True)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-1bda97f2eba1> in <module>()
----> 1 hdr.table(fill=True)

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in table(self, stream_name, fields, fill, timezone, convert_times, localize_times)
    465                                  timezone=timezone,
    466                                  convert_times=convert_times,
--> 467                                  localize_times=localize_times)
    468 
    469     def data(self, field, stream_name='primary', fill=True):

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in get_table(self, headers, stream_name, fields, fill, handler_registry, convert_times, timezone, localize_times)
   1672                     if len(table):
   1673                         if fill:
-> 1674                             table = self.fill_table(table, desc, inplace=True)
   1675                         dfs.append(table)
   1676 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in fill_table(self, table, descriptor, fields, inplace)
   2059             reg = registry_map[k]
   2060             # TODO someday we will have bulk retrieve on assets.Registry
-> 2061             table[k] = [reg.retrieve(value) for value in table[k]]
   2062 
   2063         return table

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/_core.py in <listcomp>(.0)
   2059             reg = registry_map[k]
   2060             # TODO someday we will have bulk retrieve on assets.Registry
-> 2061             table[k] = [reg.retrieve(value) for value in table[k]]
   2062 
   2063         return table

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/base_registry.py in retrieve(self, datum_id)
    176         return self._api.retrieve(self._datum_col, datum_id,
    177                                   self._datum_cache, self.get_spec_handler,
--> 178                                   logger)
    179 
    180     def get_datum(self, datum_id):

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/core.py in retrieve(col, datum_id, datum_cache, get_spec_handler, logger)
     64     datum = _get_datum_from_datum_id(col, datum_id, datum_cache, logger)
     65     handler = get_spec_handler(datum['resource'])
---> 66     return handler(**datum['datum_kwargs'])
     67 
     68 

/opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/handlers.py in __call__(self, frame, channel)
    574         # Don't read out the dataset until it is requested for the first time.
    575         self._get_dataset()
--> 576         return self._dataset[frame, channel - 1, :].squeeze()
    577 
    578     def get_roi(self, chan, bin_low, bin_high, frame=None, max_points=None):

IndexError: index 2 is out of bounds for axis 0 with size 2
```
%debug mode:
```py
BlueSky@SRX [11]: %debug
> /opt/conda_envs/collection-2018-3.1/lib/python3.6/site-packages/databroker/assets/handlers.py(576)__call__()
    574         # Don't read out the dataset until it is requested for the first time.
    575         self._get_dataset()
--> 576         return self._dataset[frame, channel - 1, :].squeeze()
    577 
    578     def get_roi(self, chan, bin_low, bin_high, frame=None, max_points=None):

ipdb> self._dataset
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])
ipdb> self._dataset.shape
(2, 3, 4096)
ipdb> frame
2
ipdb> channel
2
ipdb> 
```

**Comment by andrewmkiss** [comment] 2019-01-11 16:38
It's observed on both `collection-2018-3.1` and `collection-2019-1.0`.

**Comment by mrakitin** [comment] 2019-01-22 21:32
Would it make sense for the detector to raise is the `num > 2`? Not sure is the detector knows in advance how many counts are requested though...

**Comment by tacaswell** [comment] 2019-01-25 15:09
@mrakitin That is exactly the problem, there is not a good way to automatically inject the frame count into the devices (as plans in general do not know how many frames they are going to take either due to re-trying points or dynamic plans and in general devices do not care about the number of points.

**Comment by mrakitin** [comment] 2019-01-30 18:34
I see. I think this issue should be closed as it's working as designed/expected.

**Closed** 2019-02-13 15:01 UTC
